<h2>Your Basket</h2>
<table>
    <thead>
        <tr style="border-bottom: 1px dashed #000000">
            <th class="item-title">Product Name</th>
            <th class="item-title">P.P.U.</th>
            <th class="item-quantity">Quantity</th>
            <th class="item-title">Price</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
<?php $total = 0; ?>
<?php foreach($this->result as $martItem): ?>
    <?php
    $removeItemUrl = $this->url(
        array(
            'controller' => 'mart',
            'action'     => 'delete',
            'martID'     => $martItem['id'],
        ),
        'default',
        true);
    ?>
<tr>
    <?php
        $totalLine = ((int)$martItem['price'] * (int)$martItem['quantity']);
        $total = $total + $totalLine;
    ?>

    <td class="item-name"><?php echo $martItem['name']; ?></td>
    <td class="item-price"><?php echo $martItem['price']; ?></td>
    <td class="item-quantity"><?php echo $martItem['quantity']; ?></td>
    <td class="item-price"><?php echo money_format('%i', $totalLine); ?></td>
    <td><a href="<?php echo $removeItemUrl?>">Remove</a></td>
</tr>
<?php endforeach; ?>
    <tr style="border-top: 1px dashed #000000">
        <td colspan="2" class="item-total">Total:</td>
        <td>&nbsp;</td>
        <td class="item-price"><?php echo money_format('%i', $total)?></td>
        <td>&nbsp;</td>
    </tr>
</table>
<?php
$listUrl = $this->url(
    array(
    'controller' => 'index',
    'action'     => 'index',
    ),
    'default',
    true);
?>
<br />
Return to <a href="<?php echo $listUrl?>">Product List</a>
